### ISSUE TITLE
path to MacOS support

### ISSUE THREAD

**Issue by marbar3778** [uonai/Fortunae#4]
I ran into some issues with downloading this for mac. Are there existing issues that can be opened which the community can tackle. I would love to contribute and see this working on mac.

**Comment by uonai** [comment]
I just got my hands on a Mac this past week so I'm going to work on these bugs ASAP! Expect a working Mac version in 1 - 2 weeks.

**Comment by hugginsio** [comment]
What issues are you having running this on a Mac? It works on my machine. I'm on Catalina 10.15.5.

**Comment by tac0turtle** [comment]
I was having a file not found issue but that seems it wasnt related to mac. It seems to work fine now. I wasn't sure if there were extra things that needed to be done because Mac wasnt a supported OS on the README. 

Will close this.
